name: Dockerhub
on:
  push:
    branch: master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          tags:
            - andrkrn/idx-collector:latest
            - andrkrn/idx-collector:${{ github.sha }}
