name: dockerhub
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "yarn"
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: yarn check
        run: yarn check
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          push: true
          tags: |
            andrkrn/idx-collector:${{ github.sha }}
