name: dockerhub
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'
    timeout-minutes: 10
    steps:
      - run: |
          echo -e "$GITHUB_CONTEXT\n"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      # - name: checkout
      #   uses: actions/checkout@v2
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1.10.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # - name: build and push
      #   uses: docker/build-push-action@v2.6.1
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #       andrkrn/idx-collector:${{ github.ref }}
      #       andrkrn/idx-collector:${{ github.ref }}.${{ github.sha }}
