name: Run
on:
  schedule:
    - cron: "0 10 * * 1-5"

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: andrkrn/idx-collector
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - run: node /app/dist/index.js
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
