name: Run
on:
  schedule:
    - cron: "0 10 * * 1-5"

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run
        uses: ./
        with:
          args: node /app/dist/index.js
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
