name: Run
on:
  schedule:
    - cron: "0 10 * * 1-5"
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: run latest docker image
        run: docker run andrkrn/idx-collector:latest -e CREDENTIALS=$CREDENTIALS -e SHEET_ID=$SHEET_ID
        env:
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
